// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	Username       string             `json:"username"`
	HashedPassword string             `json:"hashedPassword"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
}
